.. requirement:: CRS_CustomAttribute_Requirement
    :category: input

.. spec:: SWA_CustomAttribute_Spec
    :custom_text:
        |br|
        This is *italic text*,
        - some bullet
        - points and ...
        .. note::
            ... a small note!
    :custom_enum: a, b, c
    :custom_refs: SMD_CustomAttribute_Unit, CRS_CustomAttribute_Requirement, dim_custom_attr

.. unit:: SMD_CustomAttribute_Unit
